package com.rubim.pcpBackEnd.DTO;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class Produto {
    private Long id;
    private String codigo;
    private String nome;
    private String descricao;
    private String unidade;
    private Integer quantidadeEstoque;
    private Integer valorUnitario;

    // Getters and Setters can be generated by Lombok
}
