package com.rubim.pcpBackEnd.DTO;

import java.math.BigDecimal;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class ProdutoDTO {
    private Long id;
	private String nome;
	private String codigo;
    private String tipo;
	private BigDecimal preco;
	private BigDecimal precoCusto;
	private String situacao;
	private String descricaoCurta;
    // Getters and Setters can be generated by Lombok
}
